version: "3"
services:
  php:
    build: ./docker/php
    user: admin
    volumes:
      - .:/www
      - ./docker/php/log:/var/log/php
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    working_dir: /www

  nginx:
    build: ./docker/nginx
    image: nginx:1.17-alpine
    ports:
      - 80:80
    volumes:
      - .:/www
      - ./docker/nginx/log:/var/log/nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  mysql:
    build: ./docker/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      TZ: 'Asia/Tokyo'
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/log:/var/log/mysql
    ports:
      - 3306:3306